# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
ZSH_THEME="blinks"

# Set to this to use case-sensitive completion
CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git django symfony2 macports github osx composer node)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
export PATH=/usr/local/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11/bin:/Users/yohan/Projets/Android/sdk/tools:/usr/local/mongodb/bin:/opt/pear/bin:/opt/google_appengine
export NODE_PATH=/opt/local/lib/node_modules
export EDITOR=vim

# Aliases
alias s2="app/console"
alias s2sr="s2 server:run"
alias s2ad="s2 assetic:dump --watch"
alias s2r="s2sr & s2ad"
alias bh="bin/behat --lang=fr -fprogress"
alias pu="phpunit --colors"
alias spu="phpunit -colors -c app"
alias wpu="watch --color -n10 phpunit --colors"
alias wspu="watch --color -n10 phpunit -c app --colors"
alias my="mysql -uroot -S/tmp/mysql.sock"
alias sp="php bin/phpspec"
alias sel="java -jar /opt/selenium.jar > /dev/null &"
alias phm="phantomjs --webdriver=4444 > /dev/null &"
alias sbuild="curl -XPOST http://composer.frequence-web.net/admin.php/config/build"

function pro {
    cd ~/Sites/$1
}

# Functions
function help {
	man -t $1 | open -f -a /Applications/Preview.app
}

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

__rvm_project_rvmrc
